[tool.black]
line-length = 99
target-version = ['py310']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-r a --cache-clear"
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore::ImportWarning"
]

[tool.mypy]
exclude = "betonyou,tests,app/services/solana.py"
follow_imports = "silent"
ignore_missing_imports = "true"
check_untyped_defs = "true"
disable_error_code = "name-defined,attr-defined,arg-type"
plugins = [ "pydantic.mypy" ]
warn_redundant_casts = true
warn_unused_ignores = true

[tool.pydantic-mypy]
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[isort]
profile = "black"